name: artifact-link
description: automatically link your artifacts to your PR or commit comments
author: beni69
icon: external-link
color: purple
inputs:
  token:
    required: true
    description: 'secrets.GITHUB_TOKEN'
  summary:
    required: false
    description: whether to post a summary (enabled by default)
    default: true
  commit:
    required: false
    description: whether to post a commit comment (enabled by default)
    default: true
  pr:
    required: false
    description: whether to post a pr comment (enabled by default)
    default: true
  group:
    required: false
    description: a regex to use to create a table instead of a list in the output (see README)

runs:
  using: 'node16'
  main: 'dist/index.js'
